# Cloudflare Pages Configuration
name = "sayari-blog"
compatibility_date = "2024-01-01"
account_id = "ab54ca2d01df4886aa0c3f240ace806d"

[build]
command = "npm run build"

[env.production]
# Environment variables for production
# These should be set in Cloudflare Pages dashboard

[env.preview]
# Environment variables for preview deployments
